#!/bin/bash

if [ -d bats ]; then
  (
    cd bats
    echo Updating bats:
    git pull
  )
else
  git clone https://github.com/sstephenson/bats.git
fi

if [ -d luaenv ]; then
  (
    cd luaenv
    echo Updating luaenv:
    git pull
  )
else
  git clone https://github.com/cehoffman/luaenv.git
fi
